export const ROUTER_PATH = {
  INVOICES_LIST: '/invoices-list',
  CREATE_INVOICE: '/create-invoice',
  EDIT_INVOICE: '/edit-invoice',
} as const

export const INVOICE_ACTION = {
  SET_IS_LOADING_INVOICES: 'invoices/SET_IS_LOADING_INVOICES',
  ADD_INVOICES: 'invoices/ADD_INVOICES',
  SET_IS_UPDATING_INVOICE: 'invoices/SET_IS_UPDATING_INVOICE',
  UPDATE_INVOICE: 'invoices/UPDATE_INVOICE',
  SET_IS_DELETING_INVOICE: 'invoices/SET_IS_DELETING_INVOICE',
  DELETE_INVOICE: 'invoices/DELETE_INVOICE',
  SET_IS_CREATING_INVOICE: 'invoices/SET_IS_CREATING_INVOICE',
  CREATE_INVOICE: 'invoices/CREATE_INVOICE',
} as const
